# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d93f4f69f402ce946e078ea10a890684cdd7ddb99d3fa29856d2c24565ad54fb0913b51fb563e2adf6a92e12981d045a602e7667e2c28d9e090df8b0228336d3
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
test:
  secret_key_base: 8e985a9ff89465c0691faf6c85297fc9de9e19500ae975532c1d9f28ad61ff0353fb612f0ffa37c4c84dc35ce279d68a8366db1fb339b2dd0bd4bb785b503017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
